name: 🚀 Deploy

concurrency:
  group: Production
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: 📦 Deploy Job
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: 📦 Install dependencies (npm ci + cache)
        run: npm ci

      - name: 🏗️ Build
        run: npx astro build

      - name: 🚀 Deploy to Cloudflare Workers
        run: npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
